local PLUGIN = PLUGIN

PLUGIN.name = "Blacklisted Creation"
PLUGIN.description = "Prevents players from creating characters with blacklisted phrases."
PLUGIN.author = "Riggs"
PLUGIN.schema = "Any"
PLUGIN.license = [[
Copyright 2024 Riggs

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]]

if ( CLIENT ) then return end

PLUGIN.phrases = {
    "ackbar",
    "adderall",
    "adolf",
    "akbar",
    "allah",
    "allota",
    "anal",
    "anime",
    "anus",
    "applesauce",
    "ardiem",
    "arse",
    "ass",
    "autist",
    "balls",
    "bastard",
    "bellic",
    "biatch",
    "biggums",
    "bigums",
    "bitch",
    "bloody",
    "blow",
    "boi",
    "bollocks",
    "bollok",
    "boner",
    "boners",
    "bonerz",
    "bong",
    "boob",
    "bootie",
    "booty",
    "boss",
    "breen",
    "brownskin",
    "bugger",
    "butt",
    "calhoun",
    "castro",
    "chimp",
    "chimpy",
    "chink",
    "chinks",
    "chong",
    "civil",
    "clitoris",
    "cocaine",
    "cock",
    "coderall",
    "combine",
    "condom",
    "coon",
    "covid",
    "cracker",
    "crap",
    "cum",
    "cunt",
    "daboss",
    "daddy",
    "dahboss",
    "damn",
    "dark",
    "darth",
    "ddos",
    "derp",
    "dev",
    "dick",
    "dildo",
    "dis",
    "doctor",
    "doe",
    "dover",
    "downie",
    "drumpf",
    "dude",
    "dyke",
    "ebola",
    "egg",
    "eight",
    "fag",
    "fagot",
    "fat",
    "feck",
    "feet",
    "felching",
    "fellate",
    "fellatio",
    "fetus",
    "fifth",
    "first",
    "fist",
    "five",
    "flange",
    "foot",
    "foreskin",
    "four",
    "fourth",
    "freeman",
    "fuck",
    "fudgepacker",
    "fuhrer",
    "gae",
    "gay",
    "god",
    "goddamn",
    "goodman",
    "gook",
    "grandma",
    "grandpa",
    "granny",
    "grimes",
    "gurra",
    "gurrazor",
    "harambe",
    "hentai",
    "himmler",
    "hitler",
    "homo",
    "idk",
    "jedi",
    "jerk",
    "jesus",
    "jewy",
    "jizz",
    "jong",
    "jongil",
    "jongun",
    "kek",
    "kleiner",
    "knob",
    "knobend",
    "kok",
    "labia",
    "last",
    "lastname",
    "lil",
    "little",
    "lmao",
    "lmfao",
    "long",
    "lord",
    "magnusson",
    "mama",
    "mao",
    "mcfaggot",
    "mcnigbig",
    "mcnigga",
    "mcnigger",
    "meme",
    "mister",
    "money",
    "monkey",
    "mrs",
    "muff",
    "mungus",
    "muslim",
    "n 1 g",
    "n i g",
    "n1gga",
    "n1gger",
    "nazi",
    "negan",
    "neger",
    "negus",
    "nigg",
    "nine",
    "ninja",
    "ninth",
    "nlgg",
    "normous",
    "normus",
    "obama",
    "omg",
    "osama",
    "overwatch",
    "papa",
    "pee",
    "penis",
    "penls",
    "pepe",
    "piss",
    "pissy",
    "pony",
    "poo",
    "porn",
    "pound",
    "prick",
    "princess",
    "protection",
    "pube",
    "pussy",
    "putin",
    "queer",
    "rasputin",
    "reich",
    "samurai",
    "satan",
    "schlong",
    "scrotum",
    "second",
    "semen",
    "server",
    "seven",
    "seventh",
    "sex",
    "sherlock",
    "shit",
    "shitter",
    "shitty",
    "short",
    "shorty",
    "shrek",
    "sith",
    "sixth",
    "size",
    "skibidi",
    "slave",
    "slut",
    "smegma",
    "snape",
    "snowden",
    "soprano",
    "soviet",
    "spartan",
    "spongebob",
    "squidward",
    "stalin",
    "stallone",
    "stoner",
    "stroker",
    "sydrome",
    "tenth",
    "terrorist",
    "testicles",
    "third",
    "three",
    "tits",
    "titties",
    "toff",
    "tosser",
    "trummp",
    "trump",
    "turd",
    "twat",
    "tyrone",
    "ugly",
    "uncle",
    "vader",
    "vagina",
    "vape",
    "vortigaunt",
    "wank",
    "wanker",
    "weed",
    "weiner",
    "whore",
    "wick",
    "willie",
    "willy",
    "wonka",
    "wtf",
}

ix.log.AddType("blacklistedPhraseCreate", function(ply, word, name)
    local format = "%s (%s) has attempted to create a character with the blacklisted word \"%s\" (%s)."
    format = format:format(ply:GetName(), ply:SteamID64(), word, name)

    return format
end)

function PLUGIN:CanPlayerCreateCharacter(ply, payload)
    local bFound = nil
    for _, phrase in ipairs(self.phrases) do
        if ( ix.util.StringMatches(payload.name, phrase) or ix.util.StringMatches(payload.description, phrase) ) then
            bFound = phrase
            break
        end
    end

    if ( bFound and isstring(bFound) and string.len(bFound) > 0 ) then
        ix.log.Add(ply, "blacklistedPhraseCreate", bFound, payload.name .. ", " .. payload.description)
        return false, "You cannot use the blacklisted phrase \"" .. bFound .. "\"."
    end
end